### ISSUE TITLE
Running the Network in Docker 

### ISSUE THREAD

**Issue by JoshuaO** [bcgov/von-network#105]
$ ./manage start-web GENESIS_URL=https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_sandbox_genesis
Unable to find image 'eclipse/che-ip:latest' locally
latest: Pulling from eclipse/che-ip
d6a5679aa3cf: Pulling fs layer     
4498fa6d0d1b: Pulling fs layer     
4498fa6d0d1b: Verifying Checksum
4498fa6d0d1b: Download complete
d6a5679aa3cf: Verifying Checksum
d6a5679aa3cf: Download complete 
d6a5679aa3cf: Pull complete
4498fa6d0d1b: Pull complete
Digest: sha256:2ac584b1bd6e6ec2379760dd90ae63b61b67f40cc6331c6bfc46e5e747b767b5
Status: Downloaded newer image for eclipse/che-ip:latest
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN] y
ERROR: pull access denied for von-network-base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by swcurran** [comment]
Two things that didn't work:

1. The GENESIS_URL=....  Needs to be put before the ./manage start rather than after.  It is setting an environment variable that is used by the ./manage script, it is not a parameter to the script.

2. You need to do `./manage build` before running any of the start commands.  That's why you are getting the ERROR at the bottom.

Please confirm and if good, close the issue.

Hope that helps!

**Comment by JoshuaO** [comment]
Thank you! I think you need to change the readme file - https://github.com/bcgov/von-network#running-the-web-server-in-docker-against-another-ledger

**Comment by swcurran** [comment]
Thanks - fixed.
