### ISSUE TITLE
New nodes

### ISSUE THREAD

**Issue by guilherme-funchal** [bcgov/von-network#134]
Hello, How I can uptade the pool with new insert node in indy-cli ?

**Comment by WadeBarnes** [comment]
Hi @guilherme-funchal,  Would you be able to provide more details regarding what you're wishing to accomplish?

`von-network` itself was developed to provide an easy to manage ledger instance for development and testing purposes.  It uses a fixed pool of 4 nodes.  Adding an additional node to the pool would require a bit of work to the docker compose file as well as the start-up scripts.  *It could even be possible to make the pool size more configurable, given some effort.*

If you are asking about how to use the `indy-cli` features of `von-network` to register a new node to and existing network (other than `von-network`), that is a completely different question, and I can help with that too.

**Comment by guilherme-funchal** [comment]
Hello, I'm not use the blockchain network with Docker. I'm started three nodes and after that I'm add another node. After that, I'm start the ledger browser with command : 

PORT=9000 GENESIS_FILE='/home/indy/ledger/serpro/pool_transactions_genesis' python3 -m server.server
 
In pool data link doesn't show information, the system show the error message "Error loading transation data"

**Comment by WadeBarnes** [comment]
@guilherme-funchal, Does your `/home/indy/ledger/serpro/pool_transactions_genesis` correctly reflect the IP addresses and configuration of the node pool you are starting up separately?  How are you starting the other nodes?  Is this all running on the same machine, or are the nodes running on a separate machine(s)?  Can you supply the log from running `PORT=9000 GENESIS_FILE='/home/indy/ledger/serpro/pool_transactions_genesis' python3 -m server.server`?

**Comment by guilherme-funchal** [comment]
There are 4 nodes in different instances with different IPs.

I start 3 with the same genesis file in the same instance where the ledger browser runs.
I start 1 manually and insert into the pool via indy-cli, it syncs with the others.

Whem I open the ledger browser in pool the error happens.

**Comment by guilherme-funchal** [comment]
Where I can get the log of ledger browser ?

**Comment by WadeBarnes** [comment]
You should be getting logs streaming to the console with your call to `PORT=9000 GENESIS_FILE='/home/indy/ledger/serpro/pool_transactions_genesis' python3 -m server.server`

**Comment by ianco** [comment]
My guess is the ledger browser doesn't have the correct genesis transactions.

Can you open the ledger browser when you are running the first 3 nodes?

**Comment by guilherme-funchal** [comment]
Yes, I can open all functions normally.

**Comment by WadeBarnes** [comment]
Here is what the ledger browser looks like when connected to the Sovrin BuilderNet (started with logging);
`./manage start-web --logs GENESIS_URL=https://raw.githubusercontent.com/sovrin-foundation/sovrin/stable/sovrin/pool_transactions_builder_genesis LEDGER_SEED=<Seed for a Privileged DID>`
- Where `LEDGER_SEED` is set to a SEED that has permissions to read the pool ledger.  Must have a Network Monitor or higher role.

![image](https://user-images.githubusercontent.com/10504350/103292263-52f13080-49a2-11eb-85d5-6f78d17407ce.png)

**Comment by guilherme-funchal** [comment]
Hi, Thanks

I will try test.

**Comment by Aberasturi** [comment]
Hello I'm having the same issue, when I started 3 additional nodes (containers) and joined them with other 4 I'm getting `Error loading transation data` when accesing `Pool` information.

That's my environment 

Von-Netowrk enviroment plus 4 containers started with von-network-base image.

We need 5 terminals (TERMINAL_VON_NETWORK, TERMINAL_NODE5, TERMINAL_NODE6, TERMINAL_NODE7 and TERMINAL_INDY_CLI)

### TERMINAL_VON_NETWORK:
From von-network directory:
./manage start


When the enviroment is started check http://$DOCKERHOST:9000/ (all working fine and can see domain, pool and configuration ledgers)


From other 3 terminals 

### TERMINAL_NODE5
docker volume create von_node5-data
docker run -ti -p 9709:9709 -p 9710:9710 --name von_node5_1 --network von_von -v von_node5-data:/home/indy/ledger von-network-base /bin/bash

### TERMINAL_NODE6
docker volume create von_node6-data
docker run -ti -p 9711:9711 -p 9712:9712 --name von_node6_1 --network von_von -v von_node6-data:/home/indy/ledger von-network-base /bin/bash

### TERMINAL_NODE7
docker volume create von_node7-data
docker run -ti -p 9713:9713 -p 9714:9714 --name von_node7_1 --network von_von -v von_node7-data:/home/indy/ledger von-network-base /bin/bash

### TERMINAL_INDY_CLI
When containers started from other terminal copy inside them `pool_transactions_genesis` and `domain_transactions_genesis files` from one of the nodes to new ones and place in /home/indy/ledger/sandbox

f.e
docker cp von_node1_1:/home/indy/ledger/sandbox/pool_transactions_genesis .
docker cp von_node1_1:/home/indy/ledger/sandbox/domain_transactions_genesis .


docker cp pool_transactions_genesis von_node[5,6,7]_1:/home/indy/ledger/sandbox/pool_transactions_genesis
docker cp domain_transactions_genesis files von_node[5,6,7]_1:/home/indy/ledger/sandbox/domain_transactions_genesis

Now in each TERMINAL_NODE[5,6,7] initialize the nodes

`init_indy_keys --name Node5 --seed 000000000000000000000000000Node5`

```
Node-stack name is Node5
Client-stack name is Node5C
Generating keys for provided seed 000000000000000000000000000Node5
Init local keys for client-stack
Public key is 3ouukk4hSmumojipxgoofs5JPZkASHWTrtJG5wfDPJQ7
Verification key is 4SWokCJWJc69Tn74VvLS6t2G2ucvXqM9FDMsWJjmsUxe
Init local keys for node-stack
Public key is 3ouukk4hSmumojipxgoofs5JPZkASHWTrtJG5wfDPJQ7
Verification key is 4SWokCJWJc69Tn74VvLS6t2G2ucvXqM9FDMsWJjmsUxe
BLS Public key is 2JSLkTGhnG3ZzGoeuZufc7V1kF5wxHqTuSUbaudhwRJzsGZupNHs5igohLnsdcYG7kFj1JGC5aV2JuiJtDtHPKBeGw24ZmBJ44YYaqfCMi5ywNyP42aSjMkvjtHrGS7oVoFbP4aG4aRaKZL3UZbbGcnGTK5kfacmBNKdPSQDyXGCoxB
Proof of possession for BLS key is QkfRaLjoiQRyY5bmsJYRiDSvUrkVTHr671vTodMKTKTfKeVuawPLhGXk2few4bo5ZMC1LFMfHhaiMfJYPTzzJbdnWuZeucWcZjgcjAcBfg5GXSNUp2swExjju359MJLb1zQMoo2yFH3VCCkgtohHA1y5AbxAmzer4Rai2ndVHtyKoV
```
before start check that we have the files /home/indy/ledger/sandbox/pool_transactions_genesis and /home/indy/ledger/sandbox/domain_transactions_genesis and then 

`start_indy_node Node5 0.0.0.0 9710 0.0.0.0 9711`


`init_indy_keys --name Node6 --seed 000000000000000000000000000Node6`

```
Node-stack name is Node6
Client-stack name is Node6C
Generating keys for provided seed 000000000000000000000000000Node6
Init local keys for client-stack
Public key is CPfw1xbhYjaPvdpgC5Q1hQNfBFoiPgUoUSTakPJ5mTmD
Verification key is Cv1Ehj43DDM5ttNBmC6VPpEfwXWwfGktHwjDJsTV5Fz8
Init local keys for node-stack
Public key is CPfw1xbhYjaPvdpgC5Q1hQNfBFoiPgUoUSTakPJ5mTmD
Verification key is Cv1Ehj43DDM5ttNBmC6VPpEfwXWwfGktHwjDJsTV5Fz8
BLS Public key is 3D5JAwAhjW5gik1ogKrnQaVrHY94e8E56iA5UifXjjYypMm2LifLiaRtgWJPiFA6uv2EiGy4MYByZ88Rmi8K3mUvb9TZeR9sdLBxsTdqrikeenac8ZVNkdCaFmGWcw8xVGqgv9cs574YDj7nuLHbJUDXN17J2fzQiD83iVQVQHW1RuU
Proof of possession for BLS key is RAMb2cWGE5K4VdTowDSCnTMi7bbHfLbELBL1XGWMSDgE5DMqGFgASmrrZnpqtyz9trDaf3VcE6LjyT72bHxR8ecPonBNUcuu5j3887C4RtVxPEkNjft2yZ2pMyYCXRiJ4bRmJMSvQa28xjXrTJ3wypzoeoa5DFA9Y6X8TLUe7hQLpP
```

before start check that we have the files /home/indy/ledger/sandbox/pool_transactions_genesis and /home/indy/ledger/sandbox/domain_transactions_genesis and then 

`start_indy_node Node6 0.0.0.0 9711 0.0.0.0 9712`


`init_indy_keys --name Node7 --seed 000000000000000000000000000Node7`

```
Node-stack name is Node7
Client-stack name is Node7C
Generating keys for provided seed 000000000000000000000000000Node7
Init local keys for client-stack
Public key is H6AmZrp7cA1gGshmRD6enB4mjN4Bh2FGZAxqKeBoBLyC
Verification key is BM8dTooz5uykCbYSAAFwKNkYfT4koomBHsSWHTDtkjhW
Init local keys for node-stack
Public key is H6AmZrp7cA1gGshmRD6enB4mjN4Bh2FGZAxqKeBoBLyC
Verification key is BM8dTooz5uykCbYSAAFwKNkYfT4koomBHsSWHTDtkjhW
BLS Public key is 4ahBpE7gVEhW2evVgS69EJeSyciwbbby67iQj4htsgdtCxxXsEHMS6oKVeEQvrBBgncHfAddQyTt7ZF1PcfMX1Gu3xsgnzBDcLzPBz6ZdoXwi3uDPEoDZHXeDp1AFj8cidhfBWzY1FfKZMvh1HYQX8zZWMw579pYs3SyNoWLNdsNd8Q
Proof of possession for BLS key is RSZqkPwZKyXxn4qwDNQ9m9hkqBbpdMCzz9pTobyxArnQbZiLkxFTStdGyDmwmyH7fRkXygyTp7ib4VJWeJitfDbZyv2yTr3ShbBWvYEkX7jGUZDdoS3EXYfAserSLsPEdL1U3Y9tuXRuEKd99VHhcem1sPop5mNn92ryKZGvv1auWP
```

before start check that we have the files /home/indy/ledger/sandbox/pool_transactions_genesis and /home/indy/ledger/sandbox/domain_transactions_genesis and then 

`start_indy_node Node7 0.0.0.0 9713 0.0.0.0 9714`


When nodes start in TERMINAL_VON_NETWORK launch 

./manage logs

I'm getting the next messages in Node1, Node2, Node3 and Node4

```
node1_1      |WARNING|zstack.py|Node1 received message from unknown remote 3ouukk4hSmumojipxgoofs5JPZkASHWTrtJG5wfDPJQ7
node3_1      |WARNING|zstack.py|Node3 received message from unknown remote 3ouukk4hSmumojipxgoofs5JPZkASHWTrtJG5wfDPJQ7
node4_1      |WARNING|zstack.py|Node4 received message from unknown remote 3ouukk4hSmumojipxgoofs5JPZkASHWTrtJG5wfDPJQ7
node2_1      |WARNING|zstack.py|Node2 received message from unknown remote 3ouukk4hSmumojipxgoofs5JPZkASHWTrtJG5wfDPJQ7

node1_1      |WARNING|zstack.py|Node1 received message from unknown remote CPfw1xbhYjaPvdpgC5Q1hQNfBFoiPgUoUSTakPJ5mTmD
node3_1      |WARNING|zstack.py|Node3 received message from unknown remote CPfw1xbhYjaPvdpgC5Q1hQNfBFoiPgUoUSTakPJ5mTmD
node4_1      |WARNING|zstack.py|Node4 received message from unknown remote CPfw1xbhYjaPvdpgC5Q1hQNfBFoiPgUoUSTakPJ5mTmD
node2_1      |WARNING|zstack.py|Node2 received message from unknown remote CPfw1xbhYjaPvdpgC5Q1hQNfBFoiPgUoUSTakPJ5mTmD

node1_1      |WARNING|zstack.py|Node1 received message from unknown remote H6AmZrp7cA1gGshmRD6enB4mjN4Bh2FGZAxqKeBoBLyC
node3_1      |WARNING|zstack.py|Node3 received message from unknown remote H6AmZrp7cA1gGshmRD6enB4mjN4Bh2FGZAxqKeBoBLyC
node4_1      |WARNING|zstack.py|Node4 received message from unknown remote H6AmZrp7cA1gGshmRD6enB4mjN4Bh2FGZAxqKeBoBLyC
node2_1      |WARNING|zstack.py|Node2 received message from unknown remote H6AmZrp7cA1gGshmRD6enB4mjN4Bh2FGZAxqKeBoBLyC
```

I think that's because I haven't registered nodes in ledger so I do from TERMINAL_INDY_CLI.

`./manage cli init-pool mylocalpool http://$DOCKERHOST:9000/genesis`

- Create a wallet
- Create trustee DID inside wallet
- Create DIDs for Node5, Node6 and Node7 inside wallet
- From DID trustee Register Node5, Node6 and Node7 DIDs as STEWARDS
- From each node DID register each NODE



```
indy> pool list
+-------------+
| Pool        |
+-------------+
| mylocalpool |
+-------------+
indy>
indy> pool connect mylocalpool
Pool "mylocalpool" has been connected
pool(mylocalpool):indy>
pool(mylocalpool):indy> wallet create wtrustee key=000000000000000000000000Trustee1
Wallet "wtrustee" has been created
pool(mylocalpool):indy> wallet open wtrustee key=000000000000000000000000Trustee1
Wallet "wtrustee" has been opened
pool(mylocalpool):wtrustee:indy> did new did=V4SGRU86Z58d6TV7PBUe6f seed=000000000000000000000000Trustee1 metadata=trustee
Did "V4SGRU86Z58d6TV7PBUe6f" has been created with "~CoRER63DVYnWZtK8uAzNbx" verkey
Metadata has been saved for DID "V4SGRU86Z58d6TV7PBUe6f"
pool(mylocalpool):wtrustee:indy> did list
+------------------------+-------------------------+----------+
| Did                    | Verkey                  | Metadata |
+------------------------+-------------------------+----------+
| V4SGRU86Z58d6TV7PBUe6f | ~CoRER63DVYnWZtK8uAzNbx | trustee  |
+------------------------+-------------------------+----------+
pool(mylocalpool):wtrustee:indy>
pool(mylocalpool):wtrustee:indy> did new did=3ouukk4hSmumojipxgoofs5JPZkASHWTrtJG5wfDPJQ7 seed=000000000000000000000000000Node5 metadata=node5
pool(mylocalpool):wtrustee:indy> did new did=CPfw1xbhYjaPvdpgC5Q1hQNfBFoiPgUoUSTakPJ5mTmD seed=000000000000000000000000000Node6 metadata=node6
pool(mylocalpool):wtrustee:indy> did new did=H6AmZrp7cA1gGshmRD6enB4mjN4Bh2FGZAxqKeBoBLyC seed=000000000000000000000000000Node7 metadata=node7
pool(mylocalpool):wtrustee:indy> did list
+----------------------------------------------+----------------------------------------------+----------+
| Did                                          | Verkey                                       | Metadata |
+----------------------------------------------+----------------------------------------------+----------+
| H6AmZrp7cA1gGshmRD6enB4mjN4Bh2FGZAxqKeBoBLyC | BM8dTooz5uykCbYSAAFwKNkYfT4koomBHsSWHTDtkjhW | node7    |
+----------------------------------------------+----------------------------------------------+----------+
| CPfw1xbhYjaPvdpgC5Q1hQNfBFoiPgUoUSTakPJ5mTmD | Cv1Ehj43DDM5ttNBmC6VPpEfwXWwfGktHwjDJsTV5Fz8 | Node6    |
+----------------------------------------------+----------------------------------------------+----------+
| 3ouukk4hSmumojipxgoofs5JPZkASHWTrtJG5wfDPJQ7 | 4SWokCJWJc69Tn74VvLS6t2G2ucvXqM9FDMsWJjmsUxe | node5    |
+----------------------------------------------+----------------------------------------------+----------+
| V4SGRU86Z58d6TV7PBUe6f                       | ~CoRER63DVYnWZtK8uAzNbx                      | trustee  |
+----------------------------------------------+----------------------------------------------+----------+
pool(mylocalpool):wtrustee:indy> did use V4SGRU86Z58d6TV7PBUe6f
Did "V4SGRU86Z58d6TV7PBUe6f" has been set as active
pool(mylocalpool):wtrustee:did(V4S...e6f):indy> ledger nym did=3ouukk4hSmumojipxgoofs5JPZkASHWTrtJG5wfDPJQ7 verkey=4SWokCJWJc69Tn74VvLS6t2G2ucvXqM9FDMsWJjmsUxe role=2 send=true
pool(mylocalpool):wtrustee:did(V4S...e6f):indy> ledger nym did=CPfw1xbhYjaPvdpgC5Q1hQNfBFoiPgUoUSTakPJ5mTmD verkey=Cv1Ehj43DDM5ttNBmC6VPpEfwXWwfGktHwjDJsTV5Fz8 role=2 send=true
pool(mylocalpool):wtrustee:did(V4S...e6f):indy> ledger nym did=H6AmZrp7cA1gGshmRD6enB4mjN4Bh2FGZAxqKeBoBLyC verkey=BM8dTooz5uykCbYSAAFwKNkYfT4koomBHsSWHTDtkjhW role=2 send=true
pool(mylocalpool):wtrustee:indy>
pool(mylocalpool):wtrustee:indy>
pool(mylocalpool):wtrustee:indy> did use 3ouukk4hSmumojipxgoofs5JPZkASHWTrtJG5wfDPJQ7
Did "3ouukk4hSmumojipxgoofs5JPZkASHWTrtJG5wfDPJQ7" has been set as active
pool(mylocalpool):wtrustee:did(3ou...JQ7):indy> ledger node target=4SWokCJWJc69Tn74VvLS6t2G2ucvXqM9FDMsWJjmsUxe alias=Node5 node_ip=192.168.65.3 node_port=9709 client_port=9710 client_ip=192.168.65.3 services=VALIDATOR blskey=2JSLkTGhnG3ZzGoeuZufc7V1kF5wxHqTuSUbaudhwRJzsGZupNHs5igohLnsdcYG7kFj1JGC5aV2JuiJtDtHPKBeGw24ZmBJ44YYaqfCMi5ywNyP42aSjMkvjtHrGS7oVoFbP4aG4aRaKZL3UZbbGcnGTK5kfacmBNKdPSQDyXGCoxB blskey_pop=QkfRaLjoiQRyY5bmsJYRiDSvUrkVTHr671vTodMKTKTfKeVuawPLhGXk2few4bo5ZMC1LFMfHhaiMfJYPTzzJbdnWuZeucWcZjgcjAcBfg5GXSNUp2swExjju359MJLb1zQMoo2yFH3VCCkgtohHA1y5AbxAmzer4Rai2ndVHtyKoV send=true

pool(mylocalpool):wtrustee:did(3ou...JQ7):indy> did use CPfw1xbhYjaPvdpgC5Q1hQNfBFoiPgUoUSTakPJ5mTmD
Did "CPfw1xbhYjaPvdpgC5Q1hQNfBFoiPgUoUSTakPJ5mTmD" has been set as active
pool(mylocalpool):wtrustee:did(CPf...TmD):indy> ledger node target=Cv1Ehj43DDM5ttNBmC6VPpEfwXWwfGktHwjDJsTV5Fz8 alias=Node6 node_ip=192.168.65.3 node_port=9711 client_port=9712 client_ip=192.168.65.3 services=VALIDATOR
5JAwAhjW5gik1ogKrnQaVrHY94e8E56iA5UifXjjYypMm2LifLiaRtgWJPiFA6uv2EiGy4MYByZ88Rmi8K3mUvb9TZeR9sdLBxsTdqrikeenac8ZVNkdCaFmGWcw8xVGqgv9cs574YDj7nuLHbJUDXN17J2fzQiD83iVQVQHW1RuU  blskey_pop=RAMb2cWGE5K4VdTowDSCnTMi7bbHfLbELBL1XGWMSDgE5DMqGFgASmrrZnpqtyz9trDaf3VcE6LjyT72bHxR8ecPonBNUcuu5j3887C4RtVxPEkNjft2yZ2pMyYCXRiJ4bRmJMSvQa28xjXrTJ3wypzoeoa5DFA9Y6X8TLUe7hQLpP send=true

pool(mylocalpool):wtrustee:did(CPf...TmD):indy> did use H6AmZrp7cA1gGshmRD6enB4mjN4Bh2FGZAxqKeBoBLyC
Did "H6AmZrp7cA1gGshmRD6enB4mjN4Bh2FGZAxqKeBoBLyC" has been set as active
pool(mylocalpool):wtrustee:did(H6A...LyC):indy> ledger node target=BM8dTooz5uykCbYSAAFwKNkYfT4koomBHsSWHTDtkjhW alias=Node7 node_ip=192.168.65.3 node_port=9713 client_port=9714 client_ip=192.168.65.3 services=VALIDATOR blskey=4ahBpE7gVEhW2evVgS69EJeSyciwbbby67iQj4htsgdtCxxXsEHMS6oKVeEQvrBBgncHfAddQyTt7ZF1PcfMX1Gu3xsgnzBDcLzPBz6ZdoXwi3uDPEoDZHXeDp1AFj8cidhfBWzY1FfKZMvh1HYQX8zZWMw579pYs3SyNoWLNdsNd8Q  blskey_pop=RSZqkPwZKyXxn4qwDNQ9m9hkqBbpdMCzz9pTobyxArnQbZiLkxFTStdGyDmwmyH7fRkXygyTp7ib4VJWeJitfDbZyv2yTr3ShbBWvYEkX7jGUZDdoS3EXYfAserSLsPEdL1U3Y9tuXRuEKd99VHhcem1sPop5mNn92ryKZGvv1auWP send=true
```


After that in TERMINAL_NODE5, TERMINAL_NODE6 and TERMINAL_NODE7 the nodes start synching, wait until synch finish.

From Ledger Browser I'm able to see the new STEWARDS transactions when I'm in DOMAIN browser. In main dashboard only get initial 4 nodes status.

Stop all.

In TERMINAL_VON_NETWORK.

CTR+c to exist from logs and
./manage stop

In TERMINAL_NODE5, TERMINAL_NODE6 and TERMINAL_NODE7 CTR+c to stop nodes.

When all is stoped, start again.

In TERMINAL_VON_NETWORK.
./manage start

In TERMINAL_NODE5, TERMINAL_NODE6 and TERMINAL_NODE7 

start_indy_node Node5 0.0.0.0 9709 0.0.0.0 9710
start_indy_node Node6 0.0.0.0 9711 0.0.0.0 9712
start_indy_node Node7 0.0.0.0 9713 0.0.0.0 9714


From Ledgder Browser now I can see 7 Nodes status, but when I'm going to POOL ledger i'm getting `Error loading transation data`.

I' have tried to star Ledger Browser with `Where LEDGER_SEED is set to a SEED that has permissions to read the pool ledger. Must have a Network Monitor or higher role.`

./manage start-web --logs GENESIS_URL=https://certix.northeurope.cloudapp.azure.com/genesisfiles/20210610.txn LEDGER_SEED=000000000000000000000000Trustee1

And the error in logs when acces to POOL ledger is:
```
webserver_1  | 2021-06-29 16:15:58,076|DEBUG|core.py|returning None
webserver_1  | 2021-06-29 16:15:58,076|ERROR|web_protocol.py|Error handling request
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
webserver_1  |     resp = await task
webserver_1  |   File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
webserver_1  |     resp = await handler(request)
webserver_1  |   File "/home/indy/server/server.py", line 157, in ledger_json
webserver_1  |     last_modified = max(last_modified, row[1]) if last_modified else row[1]
webserver_1  | TypeError: '>' not supported between instances of 'NoneType' and 'str'
webserver_1  | 2021-06-29 16:15:58,079|INFO|web_log.py|172.20.0.1 [29/Jun/2021:16:15:58 +0000] "GET /ledger/pool?page=1&page_size=10&query=&type= HTTP/1.1" 500 244 "http://localhost:9000/browse/pool" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
webserver_1  | 2021-06-29 16:17:01,649|DEBUG|anchor.py|Resyncing ledger cache: POOL
```

Many thanks

**Comment by WadeBarnes** [comment]
@Aberasturi, Why are you wanting to add additional nodes to your `von-network` instance?

**Comment by Aberasturi** [comment]
Hi Wade, I'm newbie and for learning purpose. Thinking about create VM but with docker-compose and containers is more easier.

Reviewing docker-compose and von_generate_transactions (change numnodes from 4 to 7) I think that modifiying both is posible to start 7 nodes. 7 because I want to test N=3F+1.

I'm figuring  how to implement an "on-premise" production system and want to know steps needed to add nodes to the network [add-node-to-the-pool](https://hyperledger-indy.readthedocs.io/projects/node/en/latest/add-node.html#add-node-to-the-pool) and trying to understand how logs going changing in nodes when members are added to the network.

Reviewing Ledger Browser logs and comparing when I click in Domain Ledger and in Pool Ledger I've finded that 
None > None
None > '60793029607b93c585a2cae0b9c5a2646c5450772c4534ee7dde764c3891a5d6' works fine but when is 'aa5e817d7cc626170eca175822029339a444eb0ee8f0bd20d3b0b76e566fb008' > None fails

I'm not sure why, maybe because I haven't registered new nodes properly from Indy-cli from [add-node-to-the-pool](https://hyperledger-indy.readthedocs.io/projects/node/en/latest/add-node.html#add-node-to-the-pool) 

```
As Trustee add another Steward if needed (only Steward can add a new Validator Node; a Steward can add one and only one Validator Node).
```

keep investigating.

**Comment by Aberasturi** [comment]
Hi @WadeBarnes finally I've solved doing the next change in server.py code.

At line 157

`last_modified = max(last_modified, row[1]) if last_modified else row[1]`

I have catched the exception `TypeError: '>' not supported between instances of 'NoneType' and 'str'` because the problem was
when the `last_modified` has a txId(str) and `row[1]` None. 

Finally the code has been like this:

```
try:
    last_modified = max(last_modified, row[1]) if last_modified else row[1]
except TypeError:
    last_modified = row[1]
```

Now I'm able to view Pool Ledger from Webserver.

![ledger_browser_7_nodes_01](https://user-images.githubusercontent.com/39151755/124150654-093cec00-da92-11eb-99a1-25e868a76787.png)
![ledger_browser_7_nodes_02](https://user-images.githubusercontent.com/39151755/124150667-0b9f4600-da92-11eb-874a-a235142ad55f.png)
![ledger_browser_7_nodes_03](https://user-images.githubusercontent.com/39151755/124150672-0d690980-da92-11eb-896a-4201abd956e6.png)

**Comment by WadeBarnes** [comment]
@Aberasturi, do you want to submit a PR with those updates?

**Comment by WadeBarnes** [comment]
Addressed in https://github.com/bcgov/von-network/pull/155
